package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.ProducerData;

import greendao.ProducerDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig producerDataDaoConfig;

    private final ProducerDataDao producerDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        producerDataDaoConfig = daoConfigMap.get(ProducerDataDao.class).clone();
        producerDataDaoConfig.initIdentityScope(type);

        producerDataDao = new ProducerDataDao(producerDataDaoConfig, this);

        registerDao(ProducerData.class, producerDataDao);
    }
    
    public void clear() {
        producerDataDaoConfig.getIdentityScope().clear();
    }

    public ProducerDataDao getProducerDataDao() {
        return producerDataDao;
    }

}
